spring.application.name=clinic

# The connection URL pointing to your local MySQL instance
# Replace 'your_database_name' with the actual schema name you created in Workbench
spring.datasource.url=jdbc:mysql://localhost:3306/my_clinic?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC

# Database Credentials (Root and empty password)
spring.datasource.username=root
spring.datasource.password=
# Hibernate/JPA Settings (Tells Spring how to behave with your tables)
# 'update' will automatically create/modify tables based on your Java @Entity classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect